[Service]
MemoryDenyWriteExecute=yes

NoNewPrivileges=yes

PrivateBPF=yes
DevicePolicy=closed
DeviceAllow=/dev/rfkill rw
DeviceAllow=/dev/uinput rw
PrivateTmp=yes

ProtectClock=yes
ProtectControlGroups=yes
ProtectHome=yes
ProtectHostname=yes
ProtectKernelLogs=yes
ProtectKernelModules=yes
ProtectKernelTunables=yes
ProtectProc=ptraceable
ProcSubset=pid
ProtectSystem=strict
ReadWritePaths=-/var/lib/bluetooth -/run/systemd/unit-root

RestrictAddressFamilies=AF_BLUETOOTH AF_UNIX
RestrictNamespaces=yes
RestrictRealtime=yes
RestrictSUIDSGID=yes

LockPersonality=yes
SystemCallArchitectures=native
SystemCallFilter=@system-service
SystemCallFilter=~@resources @privileged
