[Service]
AmbientCapabilities=
CapabilityBoundingSet=

MemoryDenyWriteExecute=yes

NoNewPrivileges=yes

PrivateBPF=yes
PrivateDevices=yes
PrivateTmp=yes
PrivateUsers=yes

ProtectClock=yes
ProtectControlGroups=yes
ProtectHome=yes
ProtectHostname=yes
ProtectKernelLogs=yes
ProtectKernelModules=yes
ProtectKernelTunables=yes
ProtectSystem=strict
ReadWritePaths=-/run/opendmarc -/var/spool/postfix/var/run/opendmarc

RestrictAddressFamilies=AF_INET AF_INET6 AF_UNIX
RestrictNamespaces=yes
RestrictRealtime=yes
RestrictSUIDSGID=yes

RemoveIPC=yes

LockPersonality=yes
SystemCallArchitectures=native
SystemCallFilter=@system-service
SystemCallFilter=~@resources @privileged
